name: Aashish Nathwani
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.9027726312633604
  saturation: 0.5876714992336929
  rhythmicContrast: 0.8856352656148374
purpose: []
